config/routes.rb
AnyoneFor::Application.routes.draw do

  match '/friendships/confirm', :to => 'friendships#confirm', :as => :confirm

  resources :friendships

  resources :comments

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  match '/activities/feed', :to => 'activities#feed', :as => :activity_feed
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :activities, :only => [:create, :destroy, :show]
  resources :relationships, :only => [:create, :destroy]

  root :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/activities/attend', :to => 'activities#attend', :as => :activity_attend
  match '/activities/miss', :to => 'activities#miss', :as => :activity_miss
  match 'activities/create_comment', :to => 'activities#create_comment'
  
  match '/login/facebook', :to => 'sessions#fb_login'
  match '/login/accept_token', :to => 'sessions#accept_token'
  match '/friends', :to => 'friendships#index', :as => :friends
  match '/friendship_requests', :to => 'friendships#friendship_requests', :as => :requests
  match '/request_friendship', :to => 'friendships#request_friendship',
                               :as => :request_friendship
                               
  match '/api', :to => "pages#api"

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :user_id, :friend_id
  
  belongs_to :user, :class_name => "User"
  belongs_to :friend, :class_name => "User"
  
  scope :including, lambda {|user| including(user)}
  
  after_create :notify
  
  private
    def self.including(user)
      user_ids = %(SELECT DISTINCT friend_id FROM friendships
                       WHERE user_id = :user_id)
      friend_ids = %(SELECT DISTINCT user_id FROM friendships
                       WHERE friend_id = :user_id)
      where("user_id IN (#{user_ids}) OR user_id IN (#{friend_ids}) OR user_id = :user_id",
        { :user_id => user}
      )      
    end
    
    def notify
      UserMailer.friendship_request(self.friend, self.user).deliver if
        self.friend.friend_notification
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_filter :authenticate
  # GET /friendships
  # GET /friendships.xml
  def index
    @friendships = current_user.friendships
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @friendships }
    end
  end

  def friendship_requests
    @friendship_requests = current_user.friendship_requests
  end

  def request_friendship
    @user = User.find_by_id(params[:friendship][:friend_id])
    if (!@user.nil? and !current_user.contacts.include? @user and current_user != @user)
      @friendship = current_user.friendships.build(:friend_id => @user.id)
      if @friendship.save
        flash[:notice] = "Sent friend request."
      else
        flash[:error] = "Unable to send friend request."
      end    
    else
      flash[:notice] = "Already sent friend request"
    end
    redirect_to users_path    
  end
  
  def confirm
    @friendship = current_user.friendship_requests.find_by_id(params[:friendship_id])
    @friendship.confirmed = true
    if @friendship.save
      flash[:notice] = "Friendship confirmed"
    else
      flash[:error] = "Friendship confirmation error"
    end
    redirect_to requests_path
  end


  # DELETE /friendships/1
  # DELETE /friendships/1.xml
  def destroy
    @friendship = current_user.friendships.find_by_id(params[:id])
    if @friendship.nil?
      @friendship = current_user.reverse_friendships.find_by_id(params[:id])
    end
    @friendship.destroy

    respond_to do |format|
      format.html { redirect_to friends_path}
      format.xml  { head :ok }
    end
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :requested %><br />
    <%= f.check_box :requested %>
  </div>
  <div class="field">
    <%= f.label :confirmed %><br />
    <%= f.check_box :confirmed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/friendship_requests.html.erb
<h1>Friendship requests</h1>
<% unless @friendship_requests.nil? %>
  <% @friendship_requests.each do |friendship_request| %>
    <%= link_to friendship_request.user.name, user_path(friendship_request.user) %>
    <%= link_to 'confirm', confirm_path(:friendship_id => friendship_request.id) %>
  <% end %>
<% end %>

app/views/friendships/index.html.erb
<h1>Friends</h1>
<ul>
  <% current_user.friendships.each do |friendship| %>
    <li>
      <% unless friendship.friend.nil? %>
        <%= image_tag(friendship.friend.get_pic_square) unless
              friendship.friend.get_pic_square.empty? %>
        &nbsp;
        <%= link_to friendship.friend.name, user_path(friendship.friend) %>
      <% end %>
    </li>
  <% end %>
  <% current_user.reverse_friendships.each do |friendship| %>
    <li>
      <% unless friendship.friend.nil? %>
        <%= image_tag(friendship.user.get_pic_square) unless friendship.user.get_pic_square.empty? %>
        &nbsp;
        <%= link_to friendship.user.name, user_path(friendship.user) %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Confirmed:</b>
  <%= @friendship.confirmed %>
</p>


<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>