config/routes.rb
AnyoneFor::Application.routes.draw do

  match '/friendships/confirm', :to => 'friendships#confirm', :as => :confirm

  resources :friendships

  resources :comments

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  match '/activities/feed', :to => 'activities#feed', :as => :activity_feed
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :activities, :only => [:create, :destroy, :show]
  resources :relationships, :only => [:create, :destroy]

  root :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/activities/attend', :to => 'activities#attend', :as => :activity_attend
  match '/activities/miss', :to => 'activities#miss', :as => :activity_miss
  match 'activities/create_comment', :to => 'activities#create_comment'
  
  match '/login/facebook', :to => 'sessions#fb_login'
  match '/login/accept_token', :to => 'sessions#accept_token'
  match '/friends', :to => 'friendships#index', :as => :friends
  match '/friendship_requests', :to => 'friendships#friendship_requests', :as => :requests
  match '/request_friendship', :to => 'friendships#request_friendship',
                               :as => :request_friendship
                               
  match '/api', :to => "pages#api"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :title, :location, :description, :starts_at, :ends_at

  belongs_to :user
  has_many :participations, :dependent => :destroy
  has_many :participants, :through => :participations, :source => :user
  has_many :comments, :dependent => :destroy
  
  after_save :notify

  validates :title, :presence => true, :length => { :maximum => 60 }
  validates :user_id, :presence => true

  default_scope :order => 'activities.created_at DESC'

  scope :from_friends, lambda { |user| from_friends(user)}

  def attending? user
    if user.nil?
      return false
    end
    if self.participants.find_by_id(user.id)
      return true
    else
      return false
    end
  end

  def owner
    user = User.find_by_id(self.user_id)
    return user
  end

  def owner? (user)
    self.user_id == user.id ? true : false
  end

  private
   
    def self.from_friends(user)
      friend_ids = %(SELECT DISTINCT friend_id FROM friendships
                       WHERE user_id = :user_id AND confirmed = 't')
      reverse_friend_ids = %(SELECT DISTINCT user_id FROM friendships
                       WHERE friend_id = :user_id AND confirmed = 't')
      where("user_id IN (#{friend_ids}) OR user_id IN (#{reverse_friend_ids}) OR user_id = :user_id",
        { :user_id => user}
      )
    end
    
    def notify
      self.owner.friends.each do |user|
        UserMailer.activity_created(user, self.owner, self).deliver if
          user.activity_notification
      end
      self.owner.reverse_friends.each do |user|
        UserMailer.activity_created(user, self.owner, self).deliver if
          user.activity_notification
      end
    end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
#  before_filter :authenticate
  require 'simple_time_select'
  require 'open-uri'
  require 'json'

  def feed
    if (!params[:access_token].nil? and !params[:expires].nil?)
      access_token = 'access_token='+params[:access_token]+'&expires='+params[:expires]
      @user = sign_in_with_token access_token
    end
    
    @feed = @user.feed
    @feed.each do |activity|
      user = User.find_by_id(activity["user_id"])
      activity["user_name"] = user.name
    end
    respond_to do |format|
      format.json {render :json => @feed}
    end
  end

  def show
    @activity = Activity.find(params[:id])
    @title = @activity.title
    @comment = Comment.new
    unless @activity.owner.friend_of? current_user or @activity.owner? current_user
      redirect_to root_path
      flash[:error] = "You don't have permission for this action"
    end
  end

  def create
      unless (params[:access_token].nil? or params[:expires].nil?)
        access_token = 'access_token='+params[:access_token]+'&expires='+params[:expires]
        @user = sign_in_with_token access_token
      end

      @activity  = current_user.activities.build(params[:activity])

      #params from javascript calendar (calendrical)
      params[:start_date].nil? or params[:start_date].empty? ? start_date = Time.now.strftime("%m/%d/%Y") :
                                                               start_date = Date.strptime(params[:start_date], "%d/%m/%Y")
      start_time = params[:start_time]
      #params from HTML select form
      unless params[:date].nil? and params[:time].nil?
        start_date = params[:date]
        start_time = params[:time][:"time(5i)"]
      end
    @activity.starts_at = "#{start_date} #{start_time}"
    if @activity.save
      flash[:success] = "Activity created!"
      redirect_to root_path
    else
      render 'pages/home'
    end
  end

  def destroy
  end

  def attend 
    @activity = Activity.find_by_id(params[:activity_id])
    @activity.participants.push(current_user)
    respond_to do |format|
      format.html { redirect_to :back }
      format.xml  { render :xml => @activity }
    end
  end

  def miss
    @activity = Activity.find_by_id(params[:activity_id])
    participation = @activity.participations.find_by_user_id(current_user.id)
    @activity.participations.delete(participation)
    respond_to do |format|
      format.html { redirect_to :back }
      format.xml  { render :xml => @activity }
    end
  end

  def create_comment
    @comment  = Comment.new(params[:comment])
    @comment.user_id = current_user.id
    if @comment.save
      flash[:success] = "Comment added!"
      redirect_to activity_path(params[:comment][:activity_id])
  end
  end
  
  private
  
  def sign_in_with_token(access_token)
    puts access_token
    facebook_user = JSON.parse(open("https://graph.facebook.com/me?#{access_token}").read)
      @user = User.find_by_facebook_id(facebook_user["id"])
      if @user.nil?
        @user = User.new
        @user.name = facebook_user["name"]
        @user.facebook_id = facebook_user["id"]
        @user.email = facebook_user["email"]
        @user.save
      end
    return @user
  end
end

app/views/activities/_activity.html.erb
<tr>
  <td class="activities">
    <span class="content"><%= link_to activity.title, activity %></span>
    <span class="timestamp">
      <%= time_ago_in_words(activity.created_at) %> ago.
    </span>
  </td>
</tr>

app/views/activities/_attend_form.html.erb
<% if activity.attending? current_user %>
  <% form_tag "#{activity_miss_path}" do %>
    <%= hidden_field_tag 'activity_id', activity.id %>
    <%= submit_tag 'Not attending' %>
  <% end %>
<% else %>
  <% form_tag "#{activity_attend_path}" do %>
    <%= hidden_field_tag 'activity_id', activity.id %>
    <%= submit_tag 'Attending' %>
  <% end %>
<% end %>

app/views/activities/show.html.erb
<% if @activity.owner? current_user %>
  <p>You suggested</p>
<% else %>
  <p><%= image_tag(@activity.owner.get_pic_square, :class => "small") unless
          @activity.owner.get_pic_square.empty? %>
        &nbsp;
    <%= link_to @activity.owner.name, @activity.owner %>&nbsp;suggested</p>
<% end %>
<h1><%= @activity.title %></h1>
<% unless @activity.starts_at.nil? %>
  <p>Time: <%= @activity.starts_at.strftime("%c") %></p>
<% end %>
<% unless @activity.location.nil? or @activity.location.empty? %>
  <p>Location: <%= @activity.location %></p>
<% end %>
<% unless @activity.description.nil? or @activity.description.empty? %>
  <p>Details: <br/>
     <%= @activity.description %>
  </p>
<% end %>
<% unless @activity.owner? current_user %>
  <%= render :partial => 'attend_form', :locals => {:activity => @activity} %>
<% end %>
<% unless @activity.participants.nil? or @activity.participants.empty? %>
  <p>Already confirmed</p>
  <% @activity.participants.each do |participant| %>
    <%= image_tag(participant.get_pic_square, :class => "small") unless
          participant.get_pic_square.empty? %>
        &nbsp;
    <%= link_to participant.name, participant %><br/>
  <% end %>
<% end %>

<% unless @activity.comments.nil? or @activity.comments.empty? %>
  <div>
    <p>Comments</p>
    <% @activity.comments.each do |comment| %>
      <%= image_tag(comment.author.get_pic_square, :class => "small") unless
          comment.author.get_pic_square.empty? %>
        &nbsp;    
      <%= link_to comment.author.name, comment.author %><br/>
      <%= comment.content %><br/>
    <% end %>
  </div>
<% end %>
<br/>
<% form_for @comment, :url => { :controller => 'activities', :action => "create_comment" },
                      :html => {:class => 'comment'} do |f| %>
  <%= f.text_area :content %><br/>
  <%= f.hidden_field :activity_id, {:value => @activity.id} %>
  <%= f.submit 'Comment' %>
<% end %>