config/routes.rb
AnyoneFor::Application.routes.draw do

  match '/friendships/confirm', :to => 'friendships#confirm', :as => :confirm

  resources :friendships

  resources :comments

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  match '/activities/feed', :to => 'activities#feed', :as => :activity_feed
  
  resources :sessions, :only => [:new, :create, :destroy]
  resources :activities, :only => [:create, :destroy, :show]
  resources :relationships, :only => [:create, :destroy]

  root :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/activities/attend', :to => 'activities#attend', :as => :activity_attend
  match '/activities/miss', :to => 'activities#miss', :as => :activity_miss
  match 'activities/create_comment', :to => 'activities#create_comment'
  
  match '/login/facebook', :to => 'sessions#fb_login'
  match '/login/accept_token', :to => 'sessions#accept_token'
  match '/friends', :to => 'friendships#index', :as => :friends
  match '/friendship_requests', :to => 'friendships#friendship_requests', :as => :requests
  match '/request_friendship', :to => 'friendships#request_friendship',
                               :as => :request_friendship
                               
  match '/api', :to => "pages#api"

end

app/views/layouts/_footer.html.erb
<div id="footer">
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Contact", contact_path %></li>          
  </ul>
</div>

app/views/layouts/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-28249410-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_header.html.erb
<div id="header">
  <nav class="round">
    <ul>
        <li><%= link_to "Home", root_path %></li>
      <% if signed_in? %>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Friends", friends_path %></li>
        <li><%= link_to "Friend requests", requests_path %></li>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
        <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Sign in", facebook_login_path %></li>
      <% end %>
    </ul>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag 'style', 'calendrical', :media => 'screen' %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js" %>
  <%= javascript_include_tag "jquery.calendrical" %>
  <%= csrf_meta_tag %>
</head>
<body>

  <div class="container">

    <%= render 'layouts/header' %>

    <div id="section" class="round">
      <% flash.each do |key, value| %>
        <div class="flash_<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>    
  </div>
  <%= render 'layouts/google_analytics' %>
</body>
</html>